spring:
  application:
    name: qiyu-live-api # 调用接口
  # Spring cloud
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        namespace: qiyu-live-test #自定义的命名空间

  #数据源，并进行分库分表的操作
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml # 配置文件的地址
    pool-name: qiyu-user-pool
    minimum-idle: 150
    maximum-pool-size: 300
    #connection-init-sql: select 1
    connection-timeout: 4000
    max-lifetime: 60000


dubbo:
  application:
    name: qiyu-live-user-provider
    logger: slf4j
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos
    # This will enable application-level service discovery only (the recommended service discovery method for Dubbo3).
    # For users upgrading from Dubbo2.x, please set the value to 'all' for smooth migration.
    register-mode: instance
  protocol:
    name: dubbo
    port: 9091